%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Pearl\Desktop\Edumacation\ATSC 303\Lab 12\23March2011Sounding.xls
%    Worksheet: All Levels
%
% Auto-generated by MATLAB on 06-Apr-2020 22:36:51

%% Setup the Import Options
clc
close all

opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = "All Levels";
opts.DataRange = "A2:M4309";

% Specify column names and types
opts.VariableNames = ["Times", "PhPa", "Heightm", "TdegC", "TDdegC", "RH", "vms", "ums", "DDdegN", "FFms", "FFkmh", "LondegE", "LondegN"];
opts.SelectedVariableNames = ["Times", "PhPa", "Heightm", "TdegC", "TDdegC", "RH", "vms", "ums", "DDdegN", "FFms", "FFkmh", "LondegE", "LondegN"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
data1 = readtable("C:\Users\Pearl\Desktop\Edumacation\ATSC 303\Lab 12\23March2011Sounding.xls", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Problem 1 --> Plot original
figure
plot(data1.TdegC,data1.PhPa);
hold on;
plot(data1.TDdegC,data1.PhPa);
set(gca,'Ydir','reverse');
xlabel("Temp");
ylabel("Pressure");
legend("T","TD");
hold off

%%

figure
h1=axes
plot(data1.TdegC,data1.PhPa);
hold on;
plot(data1.TDdegC,data1.PhPa);
set(h1,'Ydir','reverse');
xlabel("Temp");
ylabel("Pressure");
legend("T","TD");
hold off
%%
T_sig_points_final = zeros(10,3);
TD_sig_points_final = zeros(26,3);

for i = 1:length(T_sig)
    T_sig_points_final(i,1) = T_sig(i).Position(1);
    T_sig_points_final(i,2) = T_sig(i).Position(2);
    T_sig_points_final(i,3) = T_sig(i).DataIndex;
end


for i = 1:length(TD_sig)
    TD_sig_points_final(i,1) = TD_sig(i).Position(1);
    TD_sig_points_final(i,2) = TD_sig(i).Position(2);
    TD_sig_points_final(i,3) = TD_sig(i).DataIndex;
end

%% Find vars at each index
% P (hPa),Height (m),T (degC), TD (degC),v (m/s),u (m/s),DD (degN),FF
% (m/s),FF (km/h);




T_sig_all_points = zeros(length(T_sig_points_final),width(data1));
TD_sig_all_points = zeros(length(TD_sig_points_final),width(data1));

for i = 1:length(T_sig_points_final)
    index = T_sig_points_final(i,3);
    T_sig_all_points(i,:) = table2array(data1(index,:));
    
end

for i = 1:length(TD_sig_points_final)
    index = TD_sig_points_final(i,3);
    TD_sig_all_points(i,:) = table2array(data1(index,:));
end


%% Plot with new data SORTED
xTD=sort(TD_sig_all_points);
xT=sort(T_sig_all_points);

figure
h1=axes
plot(xT(:,4),xT(:,2),'--');
hold on
plot(xTD(:,4),xTD(:,2),'.-');
set(h1,'Ydir','reverse');
xlabel("Temp");
ylabel("Pressure");
legend("T","TD");
hold off
